# Generated by Django 4.2.6 on 2024-01-25 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('strictNumOfPlayers', models.BooleanField(default=True)),
                ('maxPlayers', models.IntegerField()),
                ('minPlayers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroToPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.game')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Создана'), (1, 'Подготовка'), (2, 'Пики, баны'), (3, 'В процессе'), (4, 'Игра окончена'), (-1, 'Отменена')], default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('duration', models.TimeField(null=True)),
                ('hash', models.CharField(db_index=True, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.game')),
            ],
        ),
        migrations.CreateModel(
            name='UserQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eloFilter', models.BooleanField()),
                ('queuedFrom', models.DateTimeField(auto_now_add=True)),
                ('targetPlayers', models.SmallIntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eloChange', models.SmallIntegerField(null=True)),
                ('place', models.SmallIntegerField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('heroToPlay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.herotoplay')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserElo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
