# Generated by Django 4.2.6 on 2024-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
