# Generated by Django 4.2.6 on 2024-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_alter_userqueue_queued_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='hash',
            field=models.CharField(db_index=True, null=True, unique=True),
        ),
    ]
