# Generated by Django 4.2.6 on 2024-02-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_match_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='celery_task_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_to_confirm',
            field=models.DateTimeField(null=True),
        ),
    ]
