# Generated by Django 4.2 on 2023-10-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friendship_delete_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
