# Generated by Django 4.2.6 on 2023-12-03 20:01

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'Данное имя пользователя занято'}, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(error_messages={'unique': 'Данный адрес электронной почты уже зарегистрирован'}, max_length=254, unique=True)),
                ('phoneNumber', models.CharField(error_messages={'unique': 'Данный номер телефона уже используется'}, max_length=25, null=True, unique=True)),
                ('steamId', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/userPhoto/')),
                ('background', models.ImageField(null=True, upload_to='images/userBackground/')),
                ('decency', models.IntegerField(default=10000)),
                ('reportsOwned', models.IntegerField(default=8)),
                ('reportsGot', models.IntegerField(default=0)),
                ('isAdmin', models.BooleanField(default=False)),
                ('inGame', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('subExpiresAt', models.DateTimeField(null=True)),
                ('banExpiresAt', models.DateTimeField(null=True)),
                ('muteExpiresAt', models.DateTimeField(null=True)),
                ('voteExpiresAt', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
