# Generated by Django 4.2.4 on 2023-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steamNickname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='images/userPhoto/'),
        ),
    ]
