# Generated by Django 4.2 on 2023-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_isbanned_user_banexpiresin_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(error_messages={'unique': 'Данный номер телефона уже используется'}, max_length=25, null=True, unique=True),
        ),
    ]
