# Generated by Django 4.2 on 2023-10-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(default='', null=True, upload_to='images/userBackground/'),
        ),
    ]
