# Generated by Django 4.2 on 2023-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(null=True, upload_to='images/userBackground/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/userPhoto/'),
        ),
    ]
