# Generated by Django 4.2 on 2023-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_background_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reports',
        ),
        migrations.AddField(
            model_name='user',
            name='muteExpiresIn',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='user',
            name='reportsGot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reportsOwned',
            field=models.IntegerField(default=8),
        ),
    ]
