env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  port: ${POSTGRES_PORT}
  host: ${POSTGRES_HOST}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db_name: ${POSTGRES_DB}