# Generated by Django 4.2.4 on 2023-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_relation_user_1_remove_relation_user_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заявка отправлена'), (1, 'Друзья')]),
        ),
    ]
