# Generated by Django 4.2.4 on 2023-08-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_photo_alter_user_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='images/userPhoto'),
        ),
    ]
