# Generated by Django 4.2.4 on 2023-08-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_steamnickname_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='steamNickname',
        ),
    ]
