# Generated by Django 4.2.4 on 2023-08-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_first_name_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='decency',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='inGame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='reports',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='steamId',
            field=models.CharField(error_messages={'unique': 'Данный steam id уже зарегистрирован'}, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subExpiresIn',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voteExpiresIn',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
