# Generated by Django 4.2.4 on 2023-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_photo_alter_user_decency_alter_user_ingame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', upload_to='images/userPhoto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='steamId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
